### ISSUE TITLE
Security issue: caller can cause DoS via EOM error on server due to no limit on incoming sizes

### ISSUE THREAD

**Issue by bwehrle** [vlingo/xoom-http#82]
There is no checks on post body size.  This can easily overwhelm services when multiple callers post huge requests.
This cap on body size should exist like it does in Tomcat, et. al. and be set to a very small default value like 1 megabyte.
 Public facing services should have this tuned to a value more appropriate for their needs and as small as possible.  It is is a best practice to use a web application firewall to mitigate DDoS surface area.

Might this be handled by Netty already?  This should be clarified as discussed below.

Mitigation:
VLINGO-HTTP servers can be placed behind a reverse proxy or application gateway which limits incoming content size.  Nginx supports this- see http://nginx.org/en/docs/http/ngx_http_core_module.html#client_max_body_size.

**Comment by bwehrle** [comment]
This also might exist for other aspects of the HTTP Request (headers, path or other elements)

**Comment by VaughnVernon** [comment]
Thanks @bwehrle! Internally we use Netty, especially on Linux-based systems due to a strange JDK error in polling socket channels on Linux. We do declare a buffer limit of 1 MB for Netty, but I don't know if this is supposed to prevent the kinds of attacks you suggest looking out for. If so then it should be covered.

This is used by all normal `ServerActor` instances, and it enables the service/application to set its own limit:

https://github.com/vlingo/xoom-http/blob/ca91fc749dda9d35f08ce5d3eb7102e2ff6c9061/src/main/java/io/vlingo/xoom/http/resource/ServerActor.java#L120

https://github.com/vlingo/xoom-wire/blob/d307b796e3fe85d0bcd3d7aa70d0ad3235d1d38d/src/main/java/io/vlingo/xoom/wire/fdx/bidirectional/netty/server/NettyServerChannelActor.java#L192

This is used when an `HttpAgent` is specifically requested:

https://github.com/vlingo/xoom-http/blob/ca91fc749dda9d35f08ce5d3eb7102e2ff6c9061/src/main/java/io/vlingo/xoom/http/resource/agent/AgentInitializer.java#L40

**Comment by bwehrle** [comment]
Let me check the underlying wire system and if its using a specified limit or if that buffer limit is sufficient.

**Comment by bwehrle** [comment]
This now makes sense:
* Body will never contain content chunks because we're using an HttpObjectAggregator
* The aggregator has a limit which is set to 1MB
* This approach applies that maximum content size (note: this value is not exposed in the configuration)
* Netty already has a default max header size as well

I think we can close this issue.
